// Meteor.subscribe('dental_staff');
// Meteor.subscribe('dental_doctor');
// Meteor.subscribe('dental_diseaseCategory');
// Meteor.subscribe('dental_diseaseItem');
// Meteor.subscribe('dental_patient');
// Meteor.subscribe('dental_supplier');
// Meteor.subscribe('dental_laboratory');
Meteor.subscribe('dental_materialCost');
// Meteor.subscribe('dental_materialCostCategory');
// Meteor.subscribe('dental_materialCostItem');
// Meteor.subscribe('dental_orderCategory');
// Meteor.subscribe('dental_orderItem');
// Meteor.subscribe('dental_patientHistory');
// Meteor.subscribe('dental_register');
Meteor.subscribe('dental_specialRegister');
Meteor.subscribe('dental_treatment');
Meteor.subscribe('dental_deposit');
Meteor.subscribe('dental_invoice');
Meteor.subscribe('dental_purchase');
Meteor.subscribe('dental_payment');
Meteor.subscribe('dental_specialPayment');
Meteor.subscribe('dental_specialTreatment');
//Meteor.subscribe('dental_quotation');
Meteor.subscribe('alertCalendarEvent');
